### ISSUE TITLE
what does 4DM stand for ???

### ISSUE THREAD

**Issue by JcsnP** [KyosaixZ/4DM#1]
![image](https://user-images.githubusercontent.com/37466531/231698949-ee20803d-daa6-405e-904d-edcb8c719f76.png)

**Comment by MangkornKW** [comment]
4th Dimension Movement: This name implies that the company is on the cutting edge of innovation and is always moving forward into the next dimension of progress.

**Comment by MangkornKW** [comment]
"4 Dog Men" is the actual name.

**Comment by JcsnP** [comment]
Should I invest in your company?. I will send 15 crates of instant noodles to your employee
![image](https://user-images.githubusercontent.com/37466531/231708068-634b1aec-0488-4e87-857c-5795d02018ca.png)

**Comment by MangkornKW** [comment]
That's good but I prefer the mala flavor from Nissin.

![nissin_vegetarian_mala_flavour_1634467814_938a5a11_progressive.jpg](https://user-images.githubusercontent.com/76460553/231799134-52ad7159-c0b3-44aa-8114-cb7ce1fc4102.jpg)

**Comment by JcsnP** [comment]
After you told me it was delicious. I went to buy at "Huamum Shop". It's not delicious at all. Your taste is terrible 🙄
![image](https://user-images.githubusercontent.com/37466531/232098342-57518841-fc75-4c41-8870-91b6e9db698d.png)

**Comment by MangkornKW** [comment]
I listen to all your opinions and can understand each other's preferences.  

Except for one thing  Maybe it would be better  If you call that shop "R้an P้a"

**Comment by JcsnP** [comment]
sorry, i mean 'Ran Pa Huamum'
